config/routes.rb
Rails.application.routes.draw do
  resources :doctors
  root 'doctors#index'
end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :address_line1, presence: true
  validates :zipcode, presence: true
  validates :city, presence: true
  validates :speciality, presence: true

  geocoded_by :address
  after_validation :geocode

  def address
    AddressBuilder.new(doctor: self).build
  end

  def full_name
    [first_name, last_name].map(&:capitalize).join(' ')
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
  scope :opening,      -> { where(kind: 'opening').first }
  scope :appointments, -> { where(kind: 'appointment') }

  class << self
    def availabilities(date = nil)
      return [] unless date
      AvailabilityFinder.new(date: date).all
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/doctors_controller.rb
# -*- coding: utf-8 -*-
class DoctorsController < ApplicationController

  before_action :set_doctor, only: [:show, :edit, :update, :destroy]

  def index
    @doctors = Doctor.all

    @markers = Gmaps4rails.build_markers(@doctors) do |doctor, marker|
      marker.lat doctor.latitude
      marker.lng doctor.longitude
    end
  end

  def show
    @markers = Gmaps4rails.build_markers(@doctor) do |doctor, marker|
      marker.lat doctor.latitude
      marker.lng doctor.longitude
    end
  end

  def new
    @doctor = Doctor.new
  end

  def edit
  end

  def create
    @doctor = Doctor.new(doctor_params)

    respond_to do |format|
      if @doctor.save
        format.html { redirect_to doctors_path, notice: 'Docteur ajouté.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @doctor.update(doctor_params)
        format.html { redirect_to doctors_path, notice: 'Docteur mis à jour.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @doctor.destroy
    respond_to do |format|
      format.html { redirect_to doctors_url, notice: 'Docteur supprimé.' }
    end
  end

  private

  def set_doctor
    @doctor = Doctor.find(params[:id])
  end

  def doctor_params
    params.require(:doctor)
      .permit(:first_name, :last_name, :address_line1, :address_line2, :zipcode, :city, :speciality)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/views/doctors/_form.html.erb
<%= form_for @doctor, :html => { :class => "form-horizontal doctor" } do |f| %>

    <% if @doctor.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@doctor.errors.count, "erreur") %> ont empéché ce docteur d'être enregistré:</h3>
      </div>
      <div class="panel-body">
        Les champs en rouge sont obligatoires.
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label 'Prénom', :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :first_name, :class => 'form-control' %>
    </div>
    <%= error_span(@doctor[:first_name]) %>
  </div>
  <div class="control-group">
    <%= f.label 'Nom', :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :last_name, :class => 'form-control' %>
    </div>
    <%= error_span(@doctor[:last_name]) %>
  </div>
  <div class="control-group">
    <%= f.label 'Adresse ligne 1', :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :address_line1, :class => 'form-control' %>
    </div>
    <%= error_span(@doctor[:address_line1]) %>
  </div>
  <div class="control-group">
    <%= f.label 'Adresse ligne 2', :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :address_line2, :class => 'form-control' %>
    </div>
    <%= error_span(@doctor[:address_line2]) %>
  </div>
  <div class="control-group">
    <%= f.label 'Code postal', :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :zipcode, :class => 'form-control' %>
    </div>
    <%= error_span(@doctor[:zipcode]) %>
  </div>
  <div class="control-group">
    <%= f.label 'Ville', :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :city, :class => 'form-control' %>
    </div>
    <%= error_span(@doctor[:city]) %>
  </div>
  <div class="control-group">
    <%= f.label 'Spécialité', :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :speciality, :class => 'form-control' %>
    </div>
    <%= error_span(@doctor[:speciality]) %>
  </div>

  <br>
  <%= f.submit 'Valider', :class => 'btn btn-primary' %>
  <%= link_to 'Annuler',
            doctors_path, :class => 'btn btn-default' %>

<% end %>

app/views/doctors/_map.html.erb
<div style='width: auto;'>
  <div id="map" style='width: auto; height: 400px;'></div>
</div>

app/views/doctors/edit.html.erb
<%- model_class = Doctor -%>
<div class="page-header">
  <h1>Editer</h1>
</div>
<%= render :partial => 'form' %>

app/views/doctors/index.html.erb
<%= render 'map' %>

<%- model_class = Doctor -%>
<div class="page-header">
  <h1>Docteurs</h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Id</th>
      <th>Nom</th>
      <th>Prénom</th>
      <th>Adresse</th>
      <th>Spécialité</th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @doctors.each do |doctor| %>
      <tr>
        <td><%= link_to doctor.id, doctor_path(doctor) %></td>
        <td><%= doctor.last_name %></td>
        <td><%= doctor.first_name %></td>
        <td><%= doctor.address %></td>
        <td><%= doctor.speciality %></td>
        <td>
          <%= link_to 'Modifier',
                      edit_doctor_path(doctor), :class => 'btn btn-default btn-xs' %>
          <%= link_to 'Supprimer',
                      doctor_path(doctor),
                      :method => :delete,
                      :data => { :confirm => 'Etes-vous sur ?' },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Ajouter un docteur',
            new_doctor_path,
            :class => 'btn btn-primary' %>

<script>
  handler = Gmaps.build('Google');
  handler.buildMap({ internal: {id: 'map'}}, function(){
    markers = handler.addMarkers(<%=raw @markers.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
  });
</script>

app/views/doctors/new.html.erb
<%- model_class = Doctor -%>
<div class="page-header">
  <h1>Ajouter docteur</h1>
</div>
<%= render :partial => 'form' %>

app/views/doctors/show.html.erb
<%= render 'map' %>

<div class="page-header">
  <h1><%= @doctor.full_name %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong>Adresse</strong></dt>
  <dd><%= @doctor.address %></dd>
  <dt><strong>Spécialité</strong></dt>
  <dd><%= @doctor.speciality %></dd>
</dl>

<%= link_to 'Revenir à la liste', doctors_path, :class => 'btn btn-default'  %>
<%= link_to 'Modifier', edit_doctor_path(@doctor), :class => 'btn btn-default' %>
<%= link_to 'Supprimer', doctor_path(@doctor),
      :method => 'delete',
      :data => { :confirm => 'Etes-vous sur ?' },
      :class => 'btn btn-danger' %>

<script>
  handler = Gmaps.build('Google');
  handler.buildMap({ internal: {id: 'map'}}, function(){
    markers = handler.addMarkers(<%=raw @markers.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
    handler.getMap().setZoom(16);
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Doctolib" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.7.0/underscore-min.js" type="text/javascript"></script>
    <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
    <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <a class="navbar-brand" href="#">Doctolib</a>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <br>
      <footer>
        <p>&copy; Julien Blanchard 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>